version: '3.1'
 
services:
 
  main:
    image: eshnil2000/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - admin
      - admin
 
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
