version: '3.1'

volumes:
  jenkins-home:

services:
 
  main:
    image: eshnil2000/jenkins-automated
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu:/home
    user: root
 
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
